### PR TITLE
Teradata dump more tables

### PR DESCRIPTION
**Pull request by okerbez**

### CODE REVIEW

**Review by shevek-google — COMMENTED** [review]
Are you planning always to run with --metadata-stats ? If so, should these be guarded within the following if() block?

The ones that prove to be valuable and cheap in the long run, I'd like to pull out, but I start cautious. What's your opinion?

**Comment by okerbez** [comment]
> Are you planning always to run with --metadata-stats ? If so, should these be guarded within the following if() block?
> 
> The ones that prove to be valuable and cheap in the long run, I'd like to pull out, but I start cautious. What's your opinion?

Sounds fair, I moved new tables inside if, and will consider your comment in future changes

**Comment by okerbez** [comment]
> Are you planning always to run with --metadata-stats ? If so, should these be guarded within the following if() block?
> 
> The ones that prove to be valuable and cheap in the long run, I'd like to pull out, but I start cautious. What's your opinion?

Sounds fair, I moved new tables inside if, and will consider your comment in future changes

**Review by shevek-google — APPROVED** [review]
Thank you.

**Pull request merged**
