### PR TITLE
Use mypy, the canonical Python type checker.

### PR DESCRIPTION
**Pull request by ajwelch4**
Note that `mypy` is an optional type checker.  Users can still modify their forks without worrying about whether their modifications type check. It is however recommended to run `make check` before submitting a PR back upstream.

### CODE REVIEW

**Review by bdw-g — COMMENTED** [review]
Looks good, but I see that type annotation syntax is new since version 3.5.
I want to verify that we think this is a reasonable version to require

**Review by paolomorandini — APPROVED** [review]

**Review by Hackerpilot — APPROVED** [review]

**Comment by shevek-google** [comment]
Note that Ubuntu Bionic LTS is still supported and uses Python 3.6.5-3.

Ubuntu Xenial and Trusty are in extended security maintenance only.

So, this is probably OK, but a bit tight for my liking.

**Comment by ajwelch4** [comment]
@shevek-google According to the [README](https://github.com/googleapis/python-storage#unsupported-python-versions) for the GCS client lib:

> Python == 3.6: the last released version which supported Python 3.6 was google-cloud-storage 2.0.0, released 2022-01-12.
>
> Python == 3.5: the last released version which supported Python 3.5 was google-cloud-storage 1.32.0, released 2020-10-16.
>
> Python == 2.7: the last released version which supported Python 2.7 was google-cloud-storage 1.44.0, released 2022-01-05.

So if we're willing and able to downgrade the GCS client lib then we can support older versions of Python.#39 

@xiashang0624 I think you upgraded the GCS client lib? Do we need `2.3.0` or can we downgrade?

**Comment by ajwelch4** [comment]
Also, I believe the type annotation syntax has been supported since 3.0. The `typing` module has only been available in the stdlib since 3.5. But there is a [backport](https://pypi.org/project/typing/) if we want to support older 3.x versions. See [here](https://stackoverflow.com/a/31029363) for more info. So I think we can support this PR for 3.0+.

I should have done [this](https://github.com/google/dwh-migration-tools/pull/39/files#diff-cfab7219da3bb36313aff4a78ea8a1e3219509ac34cfd2774021d92642ff6776L15-R63) in a separate PR. I just noticed that `pyproject.toml` was out of sync with @xiashang0624 's change to `README.md`.  I can take it out and we can address it in a separate PR that includes a downgrade of the GCS client lib if @xiashang0624 deems a downgrade worthwhile.

**Comment by xiashang0624** [comment]
> Also, I believe the type annotation syntax has been supported since 3.0. The `typing` module has only been available in the stdlib since 3.5. But there is a [backport](https://pypi.org/project/typing/) if we want to support older 3.x versions. See [here](https://stackoverflow.com/a/31029363) for more info. So I think we can support this PR for 3.0+ but ideally I'd rather not go beyond 3.6.
> 
> I should have done [this](https://github.com/google/dwh-migration-tools/pull/39/files#diff-cfab7219da3bb36313aff4a78ea8a1e3219509ac34cfd2774021d92642ff6776L15-R63) in a separate PR. I just noticed that `pyproject.toml` was out of sync with @xiashang0624 's change to `README.md`. I can take it out and we can address it in a separate PR that includes a downgrade of the GCS client lib if @xiashang0624 deems a downgrade worthwhile.



> @shevek-google According to the [README](https://github.com/googleapis/python-storage#unsupported-python-versions) for the GCS client lib:
> 
> > Python == 3.6: the last released version which supported Python 3.6 was google-cloud-storage 2.0.0, released 2022-01-12.
> > Python == 3.5: the last released version which supported Python 3.5 was google-cloud-storage 1.32.0, released 2020-10-16.
> > Python == 2.7: the last released version which supported Python 2.7 was google-cloud-storage 1.44.0, released 2022-01-05.
> 
> So if we're willing and able to downgrade the GCS client lib then we can support older versions of Python.
> 
> @xiashang0624 I think you upgraded the GCS client lib? Do we need `2.3.0` or can we downgrade?

I only used the '2.3.0' version during development so I'm not sure. Actually I don't think we have tested the compatibility matrix of Python versions vs. versions of dependencies for this tool yet. And I think this should be a task before we can declare an older version as "supported".  For example, I think `dataclasses` is also a Python 3.7+ feature https://docs.python.org/3.7/library/dataclasses.html#

**Comment by xiashang0624** [comment]
> Also, I believe the type annotation syntax has been supported since 3.0. The `typing` module has only been available in the stdlib since 3.5. But there is a [backport](https://pypi.org/project/typing/) if we want to support older 3.x versions. See [here](https://stackoverflow.com/a/31029363) for more info. So I think we can support this PR for 3.0+ but ideally I'd rather not go beyond 3.6.
> 
> I should have done [this](https://github.com/google/dwh-migration-tools/pull/39/files#diff-cfab7219da3bb36313aff4a78ea8a1e3219509ac34cfd2774021d92642ff6776L15-R63) in a separate PR. I just noticed that `pyproject.toml` was out of sync with @xiashang0624 's change to `README.md`. I can take it out and we can address it in a separate PR that includes a downgrade of the GCS client lib if @xiashang0624 deems a downgrade worthwhile.

I think what we want to do here is to test the tool using different Python versions. The GCS usage is pretty standard here so I think we can probably use an earlier version.

**Comment by xiashang0624** [comment]
This PR looks good given tool currently supports Python 3.7+, which is documented in the README already. It appears that we want to support an earlier Python version.  I created a separate task to follow-up: http://b/237219199

**Review by xiashang0624 — APPROVED** [review]

**Review by genemerrill — APPROVED** [review]
worked for me

**Pull request merged**
