### PR TITLE
Reformat all files.

### PR DESCRIPTION
**Pull request by dawidxc**
After adding the enforcement of the Google Java Style in the spotless Gradle plugin new files need to be formatted before changing. It may be easier to format all the files in one go to simplify future PRs.

### CODE REVIEW

**Review by arotenberg-google — APPROVED** [review]
Does what it says on the tin. And I confirmed it still builds locally.

**Comment by dawidxc** [comment]
Later, when I have more approvals, if I'm not able to do fast-forward merge, I intend to redo the formatting on the most up-to-date `main` instead of attempting to rebase.

**Review by damian-compilerworks — APPROVED** [review]
LGTM

**Review by mjquinn-google — APPROVED** [review]

**Comment by dawidxc** [comment]
I have created this PR by removing the `ratchetFrom` line and then running `./gradlew spotlessApply` command. I have made no other changes. I also intend to redo the formatting, if fast-forward merge is not possible.

**Review by shevek-google — APPROVED** [review]

**Pull request merged**
