### PR TITLE
Create alpha branch using manually generated v2alpha client library source code

### PR DESCRIPTION
**Pull request by gabbybarbieri**
Rather than use the generated tar.gz, unpack and use the source code within.

### CODE REVIEW

**Comment by gabbybarbieri** [comment]
It would be preferable to have the source code under some directory so it would be like `<alpha_dir_name>/google/cloud/` or `client/<alpha_dir_name>/google/cloud` to prevent confusion between it and any traditionally imported google apis. I unfortunately don't have enough python knowledge to get this to work as some of the source code also references `google.cloud.bigquery_migration_v2alpha` (e.g. google/cloud/bigquery_migration_v2alpha/services/migration_service/client.py) and can't find it because it would be <alpha_dir_name>.google.cloud.bigquery_migration_v2alpha

**Comment by ajwelch4** [comment]
The conventional way to do this would be to distribute the dependency to [PyPI](https://pypi.org/project/google-cloud-bigquery-migration/) as a [pre-release](https://peps.python.org/pep-0440/#pre-releases). Then, on the alpha branch of this repo, in `setup.py` and in `import`s we reference the pre-release version of the dependency.

**Comment by shevek-google** [comment]
@ajwelch4 Having the module code here with the client means that we can keep the two in sync. However, keeping it on PyPI means it and the alpha service are in sync. Hmm.

**Comment by ajwelch4** [comment]
> Having the module code here with the client means that we can keep the two in sync. 

That should just be a matter of updating `setup.py` in this repo and making any necessary code changes. I think we can keep track of when that needs to be done.

Having it on PyPI also makes it a lot easier for someone who wants to use the alpha service but not this client tool. Although I'm not sure how many folks that would be.

**Review by shevek-google — APPROVED** [review]
I think this is an auto approve because the thing we're aiming for here isn't the diff of this branch against its parent, it's the diff of this branch against master.

Does this branch contain commits such that they can be CP'd onto master? I can't tell from review, but I guess we'll learn as we go along.

So, structural +1 from me.

**Comment by ajwelch4** [comment]
Here's the diff against master: https://github.com/google/dwh-migration-tools/compare/main...gabbybarbieri:dwh-migration-tools:v2alpha-from-source

**Review by ajwelch4 — CHANGES_REQUESTED** [review]
Test failed. Just need to fix the `import` in `translation_type.py`.
```
> make test

nox --sessions test
+ nox --sessions test
nox > Running session test-3.7
nox > Creating virtual environment (virtualenv) using python3.7 in .nox/test-3-7
nox > python -m pip install '.[dev]'
nox > pytest 
================================================================================================= test session starts ==================================================================================================
platform linux -- Python 3.7.12, pytest-7.1.2, pluggy-1.0.0
rootdir: /usr/local/google/home/ajwelch/Documents/code/integrations/dwh-migration/dwh-migration-tools/client, configfile: pyproject.toml
collected 0 items / 1 error                                                                                                                                                                                            

======================================================================================================== ERRORS ========================================================================================================
________________________________________________________________________________ ERROR collecting tests/integration/test_translation.py ________________________________________________________________________________
ImportError while importing test module '/usr/local/google/home/ajwelch/Documents/code/integrations/dwh-migration/dwh-migration-tools/client/tests/integration/test_translation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../../../.pyenv/versions/3.7.12/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/test_translation.py:15: in <module>
    from dwh_migration_client.main import parse_args, start_translation
.nox/test-3-7/lib/python3.7/site-packages/dwh_migration_client/main.py:24: in <module>
    from dwh_migration_client import batch_sql_translator
.nox/test-3-7/lib/python3.7/site-packages/dwh_migration_client/batch_sql_translator.py:30: in <module>
    from dwh_migration_client.config import Config
.nox/test-3-7/lib/python3.7/site-packages/dwh_migration_client/config.py:25: in <module>
    from dwh_migration_client.translation_type import TranslationType
.nox/test-3-7/lib/python3.7/site-packages/dwh_migration_client/translation_type.py:17: in <module>
    from google.cloud import bigquery_migration_v2
E   ImportError: cannot import name 'bigquery_migration_v2' from 'google.cloud' (unknown location)
=============================================================================================== short test summary info ================================================================================================
ERROR tests/integration/test_translation.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================================================================================== 1 error in 1.23s ===================================================================================================
nox > Command pytest  failed with exit code 2
nox > Session test-3.7 failed.
nox > Running session test-3.8
nox > Creating virtual environment (virtualenv) using python3.8 in .nox/test-3-8
nox > python -m pip install '.[dev]'
nox > pytest 
================================================================================================= test session starts ==================================================================================================
platform linux -- Python 3.8.12, pytest-7.1.2, pluggy-1.0.0
rootdir: /usr/local/google/home/ajwelch/Documents/code/integrations/dwh-migration/dwh-migration-tools/client, configfile: pyproject.toml
collected 0 items / 1 error                                                                                                                                                                                            

======================================================================================================== ERRORS ========================================================================================================
________________________________________________________________________________ ERROR collecting tests/integration/test_translation.py ________________________________________________________________________________
ImportError while importing test module '/usr/local/google/home/ajwelch/Documents/code/integrations/dwh-migration/dwh-migration-tools/client/tests/integration/test_translation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../../../.pyenv/versions/3.8.12/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/test_translation.py:15: in <module>
    from dwh_migration_client.main import parse_args, start_translation
.nox/test-3-8/lib/python3.8/site-packages/dwh_migration_client/main.py:24: in <module>
    from dwh_migration_client import batch_sql_translator
.nox/test-3-8/lib/python3.8/site-packages/dwh_migration_client/batch_sql_translator.py:30: in <module>
    from dwh_migration_client.config import Config
.nox/test-3-8/lib/python3.8/site-packages/dwh_migration_client/config.py:25: in <module>
    from dwh_migration_client.translation_type import TranslationType
.nox/test-3-8/lib/python3.8/site-packages/dwh_migration_client/translation_type.py:17: in <module>
    from google.cloud import bigquery_migration_v2
E   ImportError: cannot import name 'bigquery_migration_v2' from 'google.cloud' (unknown location)
=============================================================================================== short test summary info ================================================================================================
ERROR tests/integration/test_translation.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================================================================================== 1 error in 1.29s ===================================================================================================
nox > Command pytest  failed with exit code 2
nox > Session test-3.8 failed.
nox > Running session test-3.9
nox > Creating virtual environment (virtualenv) using python3.9 in .nox/test-3-9
nox > python -m pip install '.[dev]'
nox > pytest 
================================================================================================= test session starts ==================================================================================================
platform linux -- Python 3.9.12, pytest-7.1.2, pluggy-1.0.0
rootdir: /usr/local/google/home/ajwelch/Documents/code/integrations/dwh-migration/dwh-migration-tools/client, configfile: pyproject.toml
collected 0 items / 1 error                                                                                                                                                                                            

======================================================================================================== ERRORS ========================================================================================================
________________________________________________________________________________ ERROR collecting tests/integration/test_translation.py ________________________________________________________________________________
ImportError while importing test module '/usr/local/google/home/ajwelch/Documents/code/integrations/dwh-migration/dwh-migration-tools/client/tests/integration/test_translation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/test_translation.py:15: in <module>
    from dwh_migration_client.main import parse_args, start_translation
.nox/test-3-9/lib/python3.9/site-packages/dwh_migration_client/main.py:24: in <module>
    from dwh_migration_client import batch_sql_translator
.nox/test-3-9/lib/python3.9/site-packages/dwh_migration_client/batch_sql_translator.py:30: in <module>
    from dwh_migration_client.config import Config
.nox/test-3-9/lib/python3.9/site-packages/dwh_migration_client/config.py:25: in <module>
    from dwh_migration_client.translation_type import TranslationType
.nox/test-3-9/lib/python3.9/site-packages/dwh_migration_client/translation_type.py:17: in <module>
    from google.cloud import bigquery_migration_v2
E   ImportError: cannot import name 'bigquery_migration_v2' from 'google.cloud' (unknown location)
=============================================================================================== short test summary info ================================================================================================
ERROR tests/integration/test_translation.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================================================================================== 1 error in 1.21s ===================================================================================================
nox > Command pytest  failed with exit code 2
nox > Session test-3.9 failed.
nox > Running session test-3.10
nox > Creating virtual environment (virtualenv) using python3.10 in .nox/test-3-10
nox > python -m pip install '.[dev]'
nox > pytest 
================================================================================================= test session starts ==================================================================================================
platform linux -- Python 3.10.1, pytest-7.1.2, pluggy-1.0.0
rootdir: /usr/local/google/home/ajwelch/Documents/code/integrations/dwh-migration/dwh-migration-tools/client, configfile: pyproject.toml
collected 0 items / 1 error                                                                                                                                                                                            

======================================================================================================== ERRORS ========================================================================================================
________________________________________________________________________________ ERROR collecting tests/integration/test_translation.py ________________________________________________________________________________
ImportError while importing test module '/usr/local/google/home/ajwelch/Documents/code/integrations/dwh-migration/dwh-migration-tools/client/tests/integration/test_translation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../../../.pyenv/versions/3.10.1/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/test_translation.py:15: in <module>
    from dwh_migration_client.main import parse_args, start_translation
.nox/test-3-10/lib/python3.10/site-packages/dwh_migration_client/main.py:24: in <module>
    from dwh_migration_client import batch_sql_translator
.nox/test-3-10/lib/python3.10/site-packages/dwh_migration_client/batch_sql_translator.py:30: in <module>
    from dwh_migration_client.config import Config
.nox/test-3-10/lib/python3.10/site-packages/dwh_migration_client/config.py:25: in <module>
    from dwh_migration_client.translation_type import TranslationType
.nox/test-3-10/lib/python3.10/site-packages/dwh_migration_client/translation_type.py:17: in <module>
    from google.cloud import bigquery_migration_v2
E   ImportError: cannot import name 'bigquery_migration_v2' from 'google.cloud' (unknown location)
=============================================================================================== short test summary info ================================================================================================
ERROR tests/integration/test_translation.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================================================================================== 1 error in 1.38s ===================================================================================================
nox > Command pytest  failed with exit code 2
nox > Session test-3.10 failed.
nox > Ran multiple sessions:
nox > * test-3.7: failed
nox > * test-3.8: failed
nox > * test-3.9: failed
nox > * test-3.10: failed
make: *** [Makefile:40: test] Error 1
```

**Pull request merged**
