### PR TITLE
[b/353527405] Add gradle version lock files

### PR DESCRIPTION
**Pull request by Hackerpilot**

### CODE REVIEW

**Review by mjquinn-google — APPROVED** [review]
Looks useful; out of curiosity, is there external motivation for this, or is this of your own initiative? I ask because AJ is looking at b/357128377 and wanted to know if that is related at all.

**Comment by Hackerpilot** [comment]
This is for b/353527405.

**Comment by shevek-google** [comment]
Why no lockfile in lib-dumper-spi?

**Comment by Hackerpilot** [comment]
> Why no lockfile in lib-dumper-spi?

Fixed

**Pull request merged**
