### PR TITLE
Add `query-log-rotation-frequency` flag for snowflake

### PR DESCRIPTION
**Pull request by ishmum123**

### CODE REVIEW

**Comment by dawidxc** [comment]
The PR title contains `query-log-frequency`, but the existing option name is `query-log-rotation-frequency`. Did you mean to use `query-log-frequency` in the PR title?

https://github.com/google/dwh-migration-tools/blob/e0ac616f75a26285c8073aebe7cd899939025002/dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java#L111

**Comment by ishmum123** [comment]
> The PR title contains `query-log-frequency`, but the existing option name is `query-log-rotation-frequency`. Did you mean to use `query-log-frequency` in the PR title?
> 
> https://github.com/google/dwh-migration-tools/blob/e0ac616f75a26285c8073aebe7cd899939025002/dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/ConnectorArguments.java#L111

My mistake! Thanks for the catch!

**Comment by Vadoid** [comment]
Time decrease about 3x with this change on 2 days lower-upper bounds test.

**Comment by ishmum123** [comment]
> Time decrease about 3x with this change on 2 days lower-upper bounds test.

Thanks a lot for checking this out!

**Review by dawidxc — APPROVED** [review]

**Pull request merged**
