### PR TITLE
Use Python f-strings.

### PR DESCRIPTION
**Pull request by ajwelch4**
If we have settled on Python 3.6+ or 3.7+ (b/237219199) then we can and should use f-strings.

### CODE REVIEW

**Review by mjquinn-google — APPROVED** [review]

**Comment by shevek-google** [comment]
I wonder if the idea of b/237219199 was to support at least BACK to 3.6, not FORWARDS from 3.6 only. What effort does this create if we ever want to support 3.5? Is there any LTS release which still ships 3.5?

**Review by Hackerpilot — APPROVED** [review]

**Comment by ajwelch4** [comment]
@shevek-google I will look into whether any distro LTS releases support 3.5. FWIW which may not be much, the [2020 JetBrains survey](https://www.jetbrains.com/lp/python-developers-survey-2020/) pegs Python <=2.7 at 6% and Python <= 3.5 at 2.8%.

**Review by xiashang0624 — APPROVED** [review]
LGTM. Another thing I learnt about Python.  Thanks!

**Comment by shevek-google** [comment]
OK, I accept the JetBrains survey, with a slight side-order of them being very new-code/developer focused, not old-sysadmin focused. So if there's ALSO no LTS release still running 3.5 then I approve this. Thank you.

**Review by bdw-g — APPROVED** [review]
Go nuts :-)

**Comment by ajwelch4** [comment]
> OK, I accept the JetBrains survey, with a slight side-order of them being very new-code/developer focused, not old-sysadmin focused. So if there's ALSO no LTS release still running 3.5 then I approve this. Thank you.

@shevek-google Agreed that the JetBrains survey likely significantly underrepresents sysadmins.

[google-cloud-bigquery-migration](https://github.com/googleapis/python-bigquery-migration/blob/main/setup.py#L46) requires Python >=3.6. So we would have to start there if we want to support <= 3.5.

Also, I analyzed [Repology](https://repology.org/project/python/versions) for Python:

- [Python <= 2.7](https://docs.google.com/spreadsheets/d/1ejl0QYH6YSbsQSQ38hRJk43B0G5mRUxDkN6_IyqEEDE/edit#gid=1096926535&fvid=1049884159)
- [Python 3.0 - 3.7](https://docs.google.com/spreadsheets/d/1ejl0QYH6YSbsQSQ38hRJk43B0G5mRUxDkN6_IyqEEDE/edit#gid=1096926535&fvid=1204682823)

I think Repology in combo with the JetBrains data suggests if we were to ever have a problem it would likely be with 2.7 before 3.5. It seems both are mainly available in repos for EOL releases or soon to be EOL releases that have 3.6+ as well.

**Comment by shevek-google** [comment]
Thank you for the analysis.

**Pull request merged**
